services:
  postgres:
    image: postgres:latest
    container_name: hrms_db
    environment:
      POSTGRES_DB: hrms_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - hrms_net

  backend:
    build: .
    container_name: hrms_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hrms_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - hrms_net
  sonar:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/hrms_db
    depends_on:
      - postgres
    networks:
      - hrms_net

volumes:
  pg_data:

networks:
  hrms_net: